// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: gen_core_users.sql

package core_repo

import (
	"context"
)

const addCoreUser = `-- name: AddCoreUser :one

INSERT INTO "public"."core_users" (email,username,password,fullname) VALUES ($1, $2, $3, $4) RETURNING id, email, username, password, fullname, public, verified, blocked, updated, created
`

type AddCoreUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Fullname string `json:"fullname"`
}

// ------------------------------ ADD ONE CORE_USERS <-> CORE_USER  ------------------------------
func (q *Queries) AddCoreUser(ctx context.Context, arg AddCoreUserParams) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, addCoreUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Fullname,
	)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const getCoreUserWithEmail = `-- name: GetCoreUserWithEmail :one
SELECT id, email, username, password, fullname, public, verified, blocked, updated, created FROM "public"."core_users" WHERE email = $1 LIMIT 1
`

func (q *Queries) GetCoreUserWithEmail(ctx context.Context, email string) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, getCoreUserWithEmail, email)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const getCoreUserWithUid = `-- name: GetCoreUserWithUid :one

SELECT id, email, username, password, fullname, public, verified, blocked, updated, created FROM "public"."core_users" WHERE id = $1 LIMIT 1
`

// ------------------------------ GET ONE CORE_USERS <== CORE_USER  ------------------------------
func (q *Queries) GetCoreUserWithUid(ctx context.Context, id int64) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, getCoreUserWithUid, id)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const getCoreUserWithUsername = `-- name: GetCoreUserWithUsername :one
SELECT id, email, username, password, fullname, public, verified, blocked, updated, created FROM "public"."core_users" WHERE username = $1 LIMIT 1
`

func (q *Queries) GetCoreUserWithUsername(ctx context.Context, username string) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, getCoreUserWithUsername, username)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const listCoreUsers = `-- name: ListCoreUsers :many

SELECT id, email, username, password, fullname, public, verified, blocked, updated, created FROM "public"."core_users"
`

// ------------------------------ GET MULTIPLE CORE_USERS <== [CORE_USERS] ------------------------------
func (q *Queries) ListCoreUsers(ctx context.Context) ([]CoreUser, error) {
	rows, err := q.db.QueryContext(ctx, listCoreUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Fullname,
			&i.Public,
			&i.Verified,
			&i.Blocked,
			&i.Updated,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreUsersWithLimit = `-- name: ListCoreUsersWithLimit :many
SELECT id, email, username, password, fullname, public, verified, blocked, updated, created FROM "public"."core_users" LIMIT $1::int
`

func (q *Queries) ListCoreUsersWithLimit(ctx context.Context, limit int32) ([]CoreUser, error) {
	rows, err := q.db.QueryContext(ctx, listCoreUsersWithLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Fullname,
			&i.Public,
			&i.Verified,
			&i.Blocked,
			&i.Updated,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreUsersWithLimitOffset = `-- name: ListCoreUsersWithLimitOffset :many
SELECT id, email, username, password, fullname, public, verified, blocked, updated, created FROM "public"."core_users" LIMIT $2::int OFFSET $1::int
`

type ListCoreUsersWithLimitOffsetParams struct {
	Offset int32 `json:"offset_"`
	Limit  int32 `json:"limit_"`
}

func (q *Queries) ListCoreUsersWithLimitOffset(ctx context.Context, arg ListCoreUsersWithLimitOffsetParams) ([]CoreUser, error) {
	rows, err := q.db.QueryContext(ctx, listCoreUsersWithLimitOffset, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Fullname,
			&i.Public,
			&i.Verified,
			&i.Blocked,
			&i.Updated,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCoreUserWithEmail = `-- name: RemoveCoreUserWithEmail :exec
DELETE FROM "public"."core_users" WHERE email = $1
`

func (q *Queries) RemoveCoreUserWithEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, removeCoreUserWithEmail, email)
	return err
}

const removeCoreUserWithUid = `-- name: RemoveCoreUserWithUid :exec

DELETE FROM "public"."core_users" WHERE id = $1
`

// ------------------------------ REMOVE ONE CORE_USERS -> nil  ------------------------------
func (q *Queries) RemoveCoreUserWithUid(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeCoreUserWithUid, id)
	return err
}

const removeCoreUserWithUsername = `-- name: RemoveCoreUserWithUsername :exec
DELETE FROM "public"."core_users" WHERE username = $1
`

func (q *Queries) RemoveCoreUserWithUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, removeCoreUserWithUsername, username)
	return err
}

const updateCoreUserBlocked = `-- name: UpdateCoreUserBlocked :one
UPDATE "public"."core_users" SET blocked = $1 WHERE id = $2 RETURNING id, email, username, password, fullname, public, verified, blocked, updated, created
`

type UpdateCoreUserBlockedParams struct {
	Blocked bool  `json:"blocked"`
	ID      int64 `json:"id"`
}

func (q *Queries) UpdateCoreUserBlocked(ctx context.Context, arg UpdateCoreUserBlockedParams) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, updateCoreUserBlocked, arg.Blocked, arg.ID)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const updateCoreUserName = `-- name: UpdateCoreUserName :one

UPDATE "public"."core_users" SET fullname = $1 WHERE id = $2 RETURNING id, email, username, password, fullname, public, verified, blocked, updated, created
`

type UpdateCoreUserNameParams struct {
	Fullname string `json:"fullname"`
	ID       int64  `json:"id"`
}

// ------------------------------ UPDATE ONE CORE_USERS <-> CORE_USERS  ------------------------------
func (q *Queries) UpdateCoreUserName(ctx context.Context, arg UpdateCoreUserNameParams) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, updateCoreUserName, arg.Fullname, arg.ID)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const updateCoreUserPassword = `-- name: UpdateCoreUserPassword :one
UPDATE "public"."core_users" SET password = $1 WHERE id = $2 RETURNING id, email, username, password, fullname, public, verified, blocked, updated, created
`

type UpdateCoreUserPasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateCoreUserPassword(ctx context.Context, arg UpdateCoreUserPasswordParams) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, updateCoreUserPassword, arg.Password, arg.ID)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const updateCoreUserPublic = `-- name: UpdateCoreUserPublic :one
UPDATE "public"."core_users" SET public = $1 WHERE id = $2 RETURNING id, email, username, password, fullname, public, verified, blocked, updated, created
`

type UpdateCoreUserPublicParams struct {
	Public bool  `json:"public"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateCoreUserPublic(ctx context.Context, arg UpdateCoreUserPublicParams) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, updateCoreUserPublic, arg.Public, arg.ID)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const updateCoreUserUsername = `-- name: UpdateCoreUserUsername :one
UPDATE "public"."core_users" SET username = $1 WHERE id = $2 RETURNING id, email, username, password, fullname, public, verified, blocked, updated, created
`

type UpdateCoreUserUsernameParams struct {
	Username string `json:"username"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateCoreUserUsername(ctx context.Context, arg UpdateCoreUserUsernameParams) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, updateCoreUserUsername, arg.Username, arg.ID)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const updateCoreUserVerified = `-- name: UpdateCoreUserVerified :one
UPDATE "public"."core_users" SET verified = $1 WHERE id = $2 RETURNING id, email, username, password, fullname, public, verified, blocked, updated, created
`

type UpdateCoreUserVerifiedParams struct {
	Verified bool  `json:"verified"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateCoreUserVerified(ctx context.Context, arg UpdateCoreUserVerifiedParams) (CoreUser, error) {
	row := q.db.QueryRowContext(ctx, updateCoreUserVerified, arg.Verified, arg.ID)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Fullname,
		&i.Public,
		&i.Verified,
		&i.Blocked,
		&i.Updated,
		&i.Created,
	)
	return i, err
}
