// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: gen_core_tables.sql

package core_repo

import (
	"context"
)

const addCoreTable = `-- name: AddCoreTable :one

INSERT INTO "public"."core_tables" (tablename,uid,columns) VALUES ($1, $2, $3) RETURNING tid, uid, tablename, columns, created_at, updated_at
`

type AddCoreTableParams struct {
	Tablename string `json:"tablename"`
	Uid       int64  `json:"uid"`
	Columns   string `json:"columns"`
}

// -------------------------- ADD CORE_TABLES <-> CORE_TABLES --------------------------
func (q *Queries) AddCoreTable(ctx context.Context, arg AddCoreTableParams) (CoreTable, error) {
	row := q.db.QueryRowContext(ctx, addCoreTable, arg.Tablename, arg.Uid, arg.Columns)
	var i CoreTable
	err := row.Scan(
		&i.Tid,
		&i.Uid,
		&i.Tablename,
		&i.Columns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoreTableWithName = `-- name: GetCoreTableWithName :one
SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" WHERE tablename = $1 LIMIT 1
`

func (q *Queries) GetCoreTableWithName(ctx context.Context, tablename string) (CoreTable, error) {
	row := q.db.QueryRowContext(ctx, getCoreTableWithName, tablename)
	var i CoreTable
	err := row.Scan(
		&i.Tid,
		&i.Uid,
		&i.Tablename,
		&i.Columns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoreTableWithTid = `-- name: GetCoreTableWithTid :one

SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" WHERE tid = $1 LIMIT 1
`

// -------------------------- GET ONE CORE_TABLES <- CORE_TABLES --------------------------
func (q *Queries) GetCoreTableWithTid(ctx context.Context, tid int64) (CoreTable, error) {
	row := q.db.QueryRowContext(ctx, getCoreTableWithTid, tid)
	var i CoreTable
	err := row.Scan(
		&i.Tid,
		&i.Uid,
		&i.Tablename,
		&i.Columns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoreTableWithTidAndUid = `-- name: GetCoreTableWithTidAndUid :one
SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" WHERE tid = $1 AND uid = $2 LIMIT 1
`

type GetCoreTableWithTidAndUidParams struct {
	Tid int64 `json:"tid"`
	Uid int64 `json:"uid"`
}

func (q *Queries) GetCoreTableWithTidAndUid(ctx context.Context, arg GetCoreTableWithTidAndUidParams) (CoreTable, error) {
	row := q.db.QueryRowContext(ctx, getCoreTableWithTidAndUid, arg.Tid, arg.Uid)
	var i CoreTable
	err := row.Scan(
		&i.Tid,
		&i.Uid,
		&i.Tablename,
		&i.Columns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoreTables = `-- name: ListCoreTables :many

SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables"
`

// ------------------------------ GET MULTIPLE CORE_TABLES <== [CORE_TABLES] ------------------------------
func (q *Queries) ListCoreTables(ctx context.Context) ([]CoreTable, error) {
	rows, err := q.db.QueryContext(ctx, listCoreTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreTable{}
	for rows.Next() {
		var i CoreTable
		if err := rows.Scan(
			&i.Tid,
			&i.Uid,
			&i.Tablename,
			&i.Columns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreTablesWithLimit = `-- name: ListCoreTablesWithLimit :many
SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" LIMIT $1::int
`

func (q *Queries) ListCoreTablesWithLimit(ctx context.Context, limit int32) ([]CoreTable, error) {
	rows, err := q.db.QueryContext(ctx, listCoreTablesWithLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreTable{}
	for rows.Next() {
		var i CoreTable
		if err := rows.Scan(
			&i.Tid,
			&i.Uid,
			&i.Tablename,
			&i.Columns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreTablesWithLimitOffset = `-- name: ListCoreTablesWithLimitOffset :many
SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" LIMIT $2::int OFFSET $1::int
`

type ListCoreTablesWithLimitOffsetParams struct {
	Offset int32 `json:"offset_"`
	Limit  int32 `json:"limit_"`
}

func (q *Queries) ListCoreTablesWithLimitOffset(ctx context.Context, arg ListCoreTablesWithLimitOffsetParams) ([]CoreTable, error) {
	rows, err := q.db.QueryContext(ctx, listCoreTablesWithLimitOffset, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreTable{}
	for rows.Next() {
		var i CoreTable
		if err := rows.Scan(
			&i.Tid,
			&i.Uid,
			&i.Tablename,
			&i.Columns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreTablesWithUid = `-- name: ListCoreTablesWithUid :many

SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" WHERE uid = $1
`

// --------------------- GET MULTIPLE CORE_TABLES OF CORE_USERS.UID <== [CORE_TABLES] ---------------------
func (q *Queries) ListCoreTablesWithUid(ctx context.Context, uid int64) ([]CoreTable, error) {
	rows, err := q.db.QueryContext(ctx, listCoreTablesWithUid, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreTable{}
	for rows.Next() {
		var i CoreTable
		if err := rows.Scan(
			&i.Tid,
			&i.Uid,
			&i.Tablename,
			&i.Columns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreTablesWithUidWithLimit = `-- name: ListCoreTablesWithUidWithLimit :many
SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" WHERE uid = $1 LIMIT $2::int
`

type ListCoreTablesWithUidWithLimitParams struct {
	Uid   int64 `json:"uid"`
	Limit int32 `json:"limit_"`
}

func (q *Queries) ListCoreTablesWithUidWithLimit(ctx context.Context, arg ListCoreTablesWithUidWithLimitParams) ([]CoreTable, error) {
	rows, err := q.db.QueryContext(ctx, listCoreTablesWithUidWithLimit, arg.Uid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreTable{}
	for rows.Next() {
		var i CoreTable
		if err := rows.Scan(
			&i.Tid,
			&i.Uid,
			&i.Tablename,
			&i.Columns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreTablesWithUidWithLimitOffset = `-- name: ListCoreTablesWithUidWithLimitOffset :many
SELECT tid, uid, tablename, columns, created_at, updated_at FROM "public"."core_tables" WHERE uid = $1 LIMIT $3::int OFFSET $2::int
`

type ListCoreTablesWithUidWithLimitOffsetParams struct {
	Uid    int64 `json:"uid"`
	Offset int32 `json:"offset_"`
	Limit  int32 `json:"limit_"`
}

func (q *Queries) ListCoreTablesWithUidWithLimitOffset(ctx context.Context, arg ListCoreTablesWithUidWithLimitOffsetParams) ([]CoreTable, error) {
	rows, err := q.db.QueryContext(ctx, listCoreTablesWithUidWithLimitOffset, arg.Uid, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreTable{}
	for rows.Next() {
		var i CoreTable
		if err := rows.Scan(
			&i.Tid,
			&i.Uid,
			&i.Tablename,
			&i.Columns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCoreTableWithUidAndName = `-- name: RemoveCoreTableWithUidAndName :exec
DELETE FROM "public"."core_tables" WHERE uid = $1 AND tablename = $2
`

type RemoveCoreTableWithUidAndNameParams struct {
	Uid       int64  `json:"uid"`
	Tablename string `json:"tablename"`
}

func (q *Queries) RemoveCoreTableWithUidAndName(ctx context.Context, arg RemoveCoreTableWithUidAndNameParams) error {
	_, err := q.db.ExecContext(ctx, removeCoreTableWithUidAndName, arg.Uid, arg.Tablename)
	return err
}

const removeCoreTableWithUidAndTid = `-- name: RemoveCoreTableWithUidAndTid :exec

DELETE FROM "public"."core_tables" WHERE uid = $1 AND tid = $2
`

type RemoveCoreTableWithUidAndTidParams struct {
	Uid int64 `json:"uid"`
	Tid int64 `json:"tid"`
}

// -------------------------- REMOVE CORE_TABLES <-> CORE_TABLES --------------------------
func (q *Queries) RemoveCoreTableWithUidAndTid(ctx context.Context, arg RemoveCoreTableWithUidAndTidParams) error {
	_, err := q.db.ExecContext(ctx, removeCoreTableWithUidAndTid, arg.Uid, arg.Tid)
	return err
}
